#!/bin/bash

if [ ! -d /opt/pbs/var/postgresql/openpbs-walltime-extender ] ; then
    chown postgres:postgres /opt/pbs/var/postgresql/ -R
    sudo -u postgres POSTGRESQL_PATH_HERE/initdb -D /opt/pbs/var/postgresql/openpbs-walltime-extender/

    sudo -u postgres POSTGRESQL_PATH_HERE/pg_ctl -D /opt/pbs/var/postgresql/openpbs-walltime-extender/ -o "-p 5455" start -w
    sudo -u postgres psql -h localhost -p 5455 -c 'CREATE DATABASE walltime_extender;'
    sudo -u postgres POSTGRESQL_PATH_HERE/pg_ctl -D /opt/pbs/var/postgresql/openpbs-walltime-extender/ stop -w
fi
